# Generated by Django 4.1.5 on 2023-03-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_homework'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'verbose_name': 'Homework', 'verbose_name_plural': 'Homework'},
        ),
    ]
